prog:main.o fonction.o
			gcc main.o fonction.o -o prog -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
	main.o:main.c
			gcc -c main.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
	screenshare.o:fonction.c
			gcc -c fonction.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
